import { useEffect } from 'react'
import { useSession, signIn, signOut } from 'next-auth/react'

import { Button } from 'antd'

import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {

  const { data: session} = useSession()  

  const loginBtn = session?<Button onClick={() => signOut()}>Sign out</Button>:<Button onClick={() => signIn()}>Sign in</Button>

  useEffect(()=>{
    console.log('session', session?.user)
  }, [session])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className='bg-black w-12'>sfdsfsdf</div>
        {loginBtn}
      </main>      
    </div>
  )
}
